package vistas;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author jl393
 */
public class visatAltas extends javax.swing.JPanel {

    /**
     * Creates new form Altas
     */
    public visatAltas() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAltas = new javax.swing.JTabbedPane();
        altasUsuario = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        nombreUsuario = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        maternoUsuario = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        paternoUsuario = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        usuarioUser = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        contraseñaUsuario = new javax.swing.JPasswordField();
        telefonoUsuario = new javax.swing.JTextField();
        btnRUsuario = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        panelProducto = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        nombreProducto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        proveedorProducto = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        categoriaProducto = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        descripcionProducto = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        compraProducto = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        ventaProducto = new javax.swing.JTextField();
        btnRProducto = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        panelProveedor = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        empresaProveedor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nombreProveedor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        telefonoProveedor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        emailProveedor = new javax.swing.JTextField();
        btnRProveedor = new javax.swing.JLabel();
        panelCategoria = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        nombreCategoria = new javax.swing.JTextField();
        btnRCategoria = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setPreferredSize(new java.awt.Dimension(1000, 850));

        panelAltas.setBackground(new java.awt.Color(255, 255, 255));
        panelAltas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        altasUsuario.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setText("Nombre");

        jLabel12.setText("Apellido materno");

        maternoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maternoUsuarioActionPerformed(evt);
            }
        });

        jLabel13.setText("Apellido paterno");

        jLabel14.setText("Usuario");

        usuarioUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioUserActionPerformed(evt);
            }
        });

        jLabel15.setText("Contraseña");

        btnRUsuario.setBackground(new java.awt.Color(255, 51, 153));
        btnRUsuario.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnRUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imaneges/usuario (1).png"))); // NOI18N
        btnRUsuario.setText("Registrar Usuario  ");
        btnRUsuario.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnRUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRUsuario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabel17.setText("Telefono");

        javax.swing.GroupLayout altasUsuarioLayout = new javax.swing.GroupLayout(altasUsuario);
        altasUsuario.setLayout(altasUsuarioLayout);
        altasUsuarioLayout.setHorizontalGroup(
            altasUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(altasUsuarioLayout.createSequentialGroup()
                .addGroup(altasUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(altasUsuarioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel17))
                    .addGroup(altasUsuarioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14))
                    .addGroup(altasUsuarioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel15))
                    .addGroup(altasUsuarioLayout.createSequentialGroup()
                        .addGap(414, 414, 414)
                        .addComponent(btnRUsuario)))
                .addContainerGap(438, Short.MAX_VALUE))
            .addGroup(altasUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(altasUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(altasUsuarioLayout.createSequentialGroup()
                        .addGroup(altasUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(telefonoUsuario)
                            .addComponent(nombreUsuario)
                            .addComponent(usuarioUser)
                            .addComponent(contraseñaUsuario))
                        .addContainerGap())
                    .addGroup(altasUsuarioLayout.createSequentialGroup()
                        .addGroup(altasUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(maternoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(altasUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, altasUsuarioLayout.createSequentialGroup()
                                .addComponent(paternoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, altasUsuarioLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(359, 359, 359))))))
        );
        altasUsuarioLayout.setVerticalGroup(
            altasUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(altasUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(altasUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(altasUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maternoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paternoUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(telefonoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usuarioUser, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contraseñaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(259, 259, 259))
        );

        panelAltas.addTab("Usuario", altasUsuario);

        panelProducto.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setText("Nombre");

        jLabel6.setText("Categoria");

        proveedorProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proveedorProductoActionPerformed(evt);
            }
        });

        jLabel7.setText("Proveedor");

        categoriaProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoriaProductoActionPerformed(evt);
            }
        });

        jLabel8.setText("Descripcion");

        jLabel9.setText("Compra");

        compraProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compraProductoActionPerformed(evt);
            }
        });

        jLabel10.setText("Venta");

        ventaProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ventaProductoActionPerformed(evt);
            }
        });

        btnRProducto.setBackground(new java.awt.Color(255, 51, 153));
        btnRProducto.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnRProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imaneges/producto (1).png"))); // NOI18N
        btnRProducto.setText("Registrar producto  ");
        btnRProducto.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnRProducto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRProducto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        txtStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStockActionPerformed(evt);
            }
        });

        jLabel18.setText("Stock");

        javax.swing.GroupLayout panelProductoLayout = new javax.swing.GroupLayout(panelProducto);
        panelProducto.setLayout(panelProductoLayout);
        panelProductoLayout.setHorizontalGroup(
            panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelProductoLayout.createSequentialGroup()
                        .addGroup(panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(ventaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelProductoLayout.createSequentialGroup()
                        .addGroup(panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(compraProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 238, Short.MAX_VALUE)
                        .addComponent(btnRProducto)
                        .addGap(133, 133, 133))
                    .addGroup(panelProductoLayout.createSequentialGroup()
                        .addGroup(panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(proveedorProducto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(descripcionProducto)
                            .addGroup(panelProductoLayout.createSequentialGroup()
                                .addGroup(panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel6))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProductoLayout.createSequentialGroup()
                        .addGroup(panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(categoriaProducto, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nombreProducto))
                        .addContainerGap())))
        );
        panelProductoLayout.setVerticalGroup(
            panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProductoLayout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(categoriaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(proveedorProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descripcionProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(8, 8, 8)
                .addGroup(panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelProductoLayout.createSequentialGroup()
                        .addComponent(compraProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ventaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnRProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(258, Short.MAX_VALUE))
        );

        panelAltas.addTab("Producto", panelProducto);

        panelProveedor.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Empresa");

        empresaProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empresaProveedorActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre");

        nombreProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreProveedorActionPerformed(evt);
            }
        });

        jLabel3.setText("Telefono");

        telefonoProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonoProveedorActionPerformed(evt);
            }
        });

        jLabel4.setText("Email");

        emailProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailProveedorActionPerformed(evt);
            }
        });

        btnRProveedor.setBackground(new java.awt.Color(255, 51, 153));
        btnRProveedor.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnRProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imaneges/proveedor (1).png"))); // NOI18N
        btnRProveedor.setText("Registrar proveedor");
        btnRProveedor.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnRProveedor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRProveedor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout panelProveedorLayout = new javax.swing.GroupLayout(panelProveedor);
        panelProveedor.setLayout(panelProveedorLayout);
        panelProveedorLayout.setHorizontalGroup(
            panelProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProveedorLayout.createSequentialGroup()
                .addGroup(panelProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelProveedorLayout.createSequentialGroup()
                        .addGroup(panelProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelProveedorLayout.createSequentialGroup()
                                .addGap(431, 431, 431)
                                .addComponent(btnRProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelProveedorLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panelProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))))
                        .addGap(0, 441, Short.MAX_VALUE))
                    .addGroup(panelProveedorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(emailProveedor)
                            .addComponent(telefonoProveedor)
                            .addComponent(nombreProveedor)
                            .addComponent(empresaProveedor))))
                .addContainerGap())
        );
        panelProveedorLayout.setVerticalGroup(
            panelProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProveedorLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(empresaProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nombreProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(telefonoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(202, Short.MAX_VALUE))
        );

        panelAltas.addTab("Proveedor", panelProveedor);

        panelCategoria.setBackground(new java.awt.Color(255, 255, 255));

        jLabel16.setText("Nombre de la categoria");

        nombreCategoria.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        nombreCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreCategoriaActionPerformed(evt);
            }
        });

        btnRCategoria.setBackground(new java.awt.Color(255, 51, 153));
        btnRCategoria.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnRCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imaneges/categoria (1).png"))); // NOI18N
        btnRCategoria.setText("Registrar categoria");
        btnRCategoria.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnRCategoria.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRCategoria.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout panelCategoriaLayout = new javax.swing.GroupLayout(panelCategoria);
        panelCategoria.setLayout(panelCategoriaLayout);
        panelCategoriaLayout.setHorizontalGroup(
            panelCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCategoriaLayout.createSequentialGroup()
                .addGroup(panelCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCategoriaLayout.createSequentialGroup()
                        .addGroup(panelCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCategoriaLayout.createSequentialGroup()
                                .addGap(408, 408, 408)
                                .addComponent(btnRCategoria))
                            .addGroup(panelCategoriaLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel16)))
                        .addGap(0, 439, Short.MAX_VALUE))
                    .addGroup(panelCategoriaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(nombreCategoria)))
                .addContainerGap())
        );
        panelCategoriaLayout.setVerticalGroup(
            panelCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCategoriaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombreCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(145, 145, 145)
                .addComponent(btnRCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(415, Short.MAX_VALUE))
        );

        panelAltas.addTab("Categoria", panelCategoria);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAltas)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAltas)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nombreProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreProveedorActionPerformed

    private void empresaProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empresaProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empresaProveedorActionPerformed

    private void telefonoProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonoProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonoProveedorActionPerformed

    private void emailProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailProveedorActionPerformed

    private void compraProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compraProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_compraProductoActionPerformed

    private void ventaProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ventaProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ventaProductoActionPerformed

    private void categoriaProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoriaProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoriaProductoActionPerformed

    private void proveedorProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proveedorProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_proveedorProductoActionPerformed

    private void maternoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maternoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maternoUsuarioActionPerformed

    private void nombreCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreCategoriaActionPerformed

    private void usuarioUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioUserActionPerformed

    private void txtStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStockActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel altasUsuario;
    public javax.swing.JLabel btnRCategoria;
    public javax.swing.JLabel btnRProducto;
    public javax.swing.JLabel btnRProveedor;
    public javax.swing.JLabel btnRUsuario;
    public javax.swing.JComboBox<String> categoriaProducto;
    public javax.swing.JTextField compraProducto;
    public javax.swing.JPasswordField contraseñaUsuario;
    public javax.swing.JTextField descripcionProducto;
    public javax.swing.JTextField emailProveedor;
    public javax.swing.JTextField empresaProveedor;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel15;
    public javax.swing.JLabel jLabel16;
    public javax.swing.JLabel jLabel17;
    public javax.swing.JLabel jLabel18;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JTextField maternoUsuario;
    public javax.swing.JTextField nombreCategoria;
    public javax.swing.JTextField nombreProducto;
    public javax.swing.JTextField nombreProveedor;
    public javax.swing.JTextField nombreUsuario;
    private javax.swing.JTabbedPane panelAltas;
    public javax.swing.JPanel panelCategoria;
    public javax.swing.JPanel panelProducto;
    public javax.swing.JPanel panelProveedor;
    public javax.swing.JTextField paternoUsuario;
    public javax.swing.JComboBox<String> proveedorProducto;
    public javax.swing.JTextField telefonoProveedor;
    public javax.swing.JTextField telefonoUsuario;
    public javax.swing.JTextField txtStock;
    public javax.swing.JTextField usuarioUser;
    public javax.swing.JTextField ventaProducto;
    // End of variables declaration//GEN-END:variables
}
