package vistas;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author jl393
 */
public class vistaConsultas extends javax.swing.JPanel {

    /**
     * Creates new form consultasListado
     */
    public vistaConsultas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        CUsusarios = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        referenciaUsuario = new javax.swing.JTextField();
        listadoUsuario = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblUsuario = new javax.swing.JTable();
        cambiosUsuarios = new javax.swing.JLabel();
        CProductos = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        referenciaProducto = new javax.swing.JTextField();
        listadoProducto = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblConsulta = new javax.swing.JTable();
        cambiosProductos = new javax.swing.JLabel();
        CProveedor = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        referenciaProveedor = new javax.swing.JTextField();
        listadoProveedor = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProveedor = new javax.swing.JTable();
        cambiosProveedor = new javax.swing.JLabel();
        CCat = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        referenciaCat = new javax.swing.JTextField();
        listadoCat = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCat = new javax.swing.JTable();
        cambiosCategoria = new javax.swing.JLabel();

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        CUsusarios.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setText("Usuario");

        listadoUsuario.setBackground(new java.awt.Color(255, 51, 153));
        listadoUsuario.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        listadoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imaneges/listado.png"))); // NOI18N
        listadoUsuario.setText("Listado de usuario");
        listadoUsuario.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        listadoUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        listadoUsuario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        tblUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tblUsuario);

        cambiosUsuarios.setBackground(new java.awt.Color(255, 51, 153));
        cambiosUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        cambiosUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imaneges/cambio (1).png"))); // NOI18N
        cambiosUsuarios.setText(" Rregistrar Cambios  ");
        cambiosUsuarios.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        cambiosUsuarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cambiosUsuarios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout CUsusariosLayout = new javax.swing.GroupLayout(CUsusarios);
        CUsusarios.setLayout(CUsusariosLayout);
        CUsusariosLayout.setHorizontalGroup(
            CUsusariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CUsusariosLayout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(listadoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cambiosUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(322, 322, 322))
            .addGroup(CUsusariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CUsusariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(referenciaUsuario)
                    .addGroup(CUsusariosLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(0, 1260, Short.MAX_VALUE))
                    .addComponent(jScrollPane4))
                .addContainerGap())
        );
        CUsusariosLayout.setVerticalGroup(
            CUsusariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CUsusariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(referenciaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CUsusariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cambiosUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listadoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))
                .addContainerGap(334, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Usuario", CUsusarios);

        CProductos.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setText("Nombre");

        listadoProducto.setBackground(new java.awt.Color(255, 51, 153));
        listadoProducto.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        listadoProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imaneges/producto (1).png"))); // NOI18N
        listadoProducto.setText("Consultar producto  ");
        listadoProducto.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        listadoProducto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        listadoProducto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        tblConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblConsulta);

        cambiosProductos.setBackground(new java.awt.Color(255, 51, 153));
        cambiosProductos.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        cambiosProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imaneges/cambio (1).png"))); // NOI18N
        cambiosProductos.setText(" Rregistrar Cambios  ");
        cambiosProductos.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        cambiosProductos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cambiosProductos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout CProductosLayout = new javax.swing.GroupLayout(CProductos);
        CProductos.setLayout(CProductosLayout);
        CProductosLayout.setHorizontalGroup(
            CProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CProductosLayout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(listadoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cambiosProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(299, 299, 299))
            .addGroup(CProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(referenciaProducto, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(CProductosLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 1228, Short.MAX_VALUE)))
                .addContainerGap())
        );
        CProductosLayout.setVerticalGroup(
            CProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(referenciaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cambiosProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listadoProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))
                .addGap(0, 310, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Producto", CProductos);

        CProveedor.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Empresa/ID");

        referenciaProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                referenciaProveedorActionPerformed(evt);
            }
        });

        listadoProveedor.setBackground(new java.awt.Color(255, 51, 153));
        listadoProveedor.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        listadoProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imaneges/listado.png"))); // NOI18N
        listadoProveedor.setText("Listado de proveedores");
        listadoProveedor.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        listadoProveedor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        listadoProveedor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        tblProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblProveedor);

        cambiosProveedor.setBackground(new java.awt.Color(255, 51, 153));
        cambiosProveedor.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        cambiosProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imaneges/cambio (1).png"))); // NOI18N
        cambiosProveedor.setText(" Rregistrar Cambios  ");
        cambiosProveedor.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        cambiosProveedor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cambiosProveedor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout CProveedorLayout = new javax.swing.GroupLayout(CProveedor);
        CProveedor.setLayout(CProveedorLayout);
        CProveedorLayout.setHorizontalGroup(
            CProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CProveedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(CProveedorLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(1232, Short.MAX_VALUE))
                    .addGroup(CProveedorLayout.createSequentialGroup()
                        .addGroup(CProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2)
                            .addComponent(referenciaProveedor))
                        .addContainerGap())
                    .addGroup(CProveedorLayout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(listadoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cambiosProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(293, 293, 293))))
        );
        CProveedorLayout.setVerticalGroup(
            CProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CProveedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(referenciaProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cambiosProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listadoProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))
                .addContainerGap(305, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Proveedor", CProveedor);

        CCat.setBackground(new java.awt.Color(255, 255, 255));

        jLabel16.setText("Nombre de la categoria");

        referenciaCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                referenciaCatActionPerformed(evt);
            }
        });

        listadoCat.setBackground(new java.awt.Color(255, 51, 153));
        listadoCat.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        listadoCat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imaneges/listado.png"))); // NOI18N
        listadoCat.setText("Listado de categoria");
        listadoCat.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        listadoCat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        listadoCat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        tblCat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblCat);

        cambiosCategoria.setBackground(new java.awt.Color(255, 51, 153));
        cambiosCategoria.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        cambiosCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imaneges/cambio (1).png"))); // NOI18N
        cambiosCategoria.setText(" Rregistrar Cambios  ");
        cambiosCategoria.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        cambiosCategoria.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cambiosCategoria.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout CCatLayout = new javax.swing.GroupLayout(CCat);
        CCat.setLayout(CCatLayout);
        CCatLayout.setHorizontalGroup(
            CCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CCatLayout.createSequentialGroup()
                .addGap(283, 283, 283)
                .addComponent(listadoCat, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 424, Short.MAX_VALUE)
                .addComponent(cambiosCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(255, 255, 255))
            .addGroup(CCatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(referenciaCat, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(CCatLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        CCatLayout.setVerticalGroup(
            CCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CCatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(referenciaCat, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(listadoCat, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cambiosCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(315, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Categoria", CCat);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void referenciaProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_referenciaProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_referenciaProveedorActionPerformed

    private void referenciaCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_referenciaCatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_referenciaCatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel CCat;
    public javax.swing.JPanel CProductos;
    public javax.swing.JPanel CProveedor;
    public javax.swing.JPanel CUsusarios;
    public javax.swing.JLabel cambiosCategoria;
    public javax.swing.JLabel cambiosProductos;
    public javax.swing.JLabel cambiosProveedor;
    public javax.swing.JLabel cambiosUsuarios;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel16;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JLabel listadoCat;
    public javax.swing.JLabel listadoProducto;
    public javax.swing.JLabel listadoProveedor;
    public javax.swing.JLabel listadoUsuario;
    public javax.swing.JTextField referenciaCat;
    public javax.swing.JTextField referenciaProducto;
    public javax.swing.JTextField referenciaProveedor;
    public javax.swing.JTextField referenciaUsuario;
    public javax.swing.JTable tblCat;
    public javax.swing.JTable tblConsulta;
    public javax.swing.JTable tblProveedor;
    public javax.swing.JTable tblUsuario;
    // End of variables declaration//GEN-END:variables
}
