package vistas;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author jl393
 */
public class vistaConsultas extends javax.swing.JPanel {

    /**
     * Creates new form consultasListado
     */
    public vistaConsultas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        CUsusarios = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        referenciaUsuario = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        listadoUsuario = new javax.swing.JLabel();
        consultaUsuario = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblUsuario = new javax.swing.JTable();
        CProductos = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        referenciaProducto = new javax.swing.JTextField();
        listadoProducto = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        consultaProducto = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblConsulta = new javax.swing.JTable();
        CProveedor = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        referenciaProveedor = new javax.swing.JTextField();
        listadoProveedor = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        consultaProveedor = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProveedor = new javax.swing.JTable();
        CCat = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        referenciaCat = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        listadoCat = new javax.swing.JLabel();
        consultaCat = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCat = new javax.swing.JTable();

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        CUsusarios.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setText("Usuario");

        jPanel6.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 307, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 702, Short.MAX_VALUE)
        );

        listadoUsuario.setBackground(new java.awt.Color(255, 51, 153));
        listadoUsuario.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        listadoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imaneges/listado.png"))); // NOI18N
        listadoUsuario.setText("Listado de usuario");
        listadoUsuario.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        listadoUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        listadoUsuario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        consultaUsuario.setBackground(new java.awt.Color(255, 51, 153));
        consultaUsuario.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        consultaUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imaneges/Conuslta.png"))); // NOI18N
        consultaUsuario.setText("Consultar usuario");
        consultaUsuario.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        consultaUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        consultaUsuario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        tblUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tblUsuario);

        javax.swing.GroupLayout CUsusariosLayout = new javax.swing.GroupLayout(CUsusarios);
        CUsusarios.setLayout(CUsusariosLayout);
        CUsusariosLayout.setHorizontalGroup(
            CUsusariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CUsusariosLayout.createSequentialGroup()
                .addGroup(CUsusariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CUsusariosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(CUsusariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(referenciaUsuario)
                            .addGroup(CUsusariosLayout.createSequentialGroup()
                                .addGroup(CUsusariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 718, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 175, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(CUsusariosLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(listadoUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(consultaUsuario)
                        .addGap(120, 120, 120)))
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        CUsusariosLayout.setVerticalGroup(
            CUsusariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CUsusariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(referenciaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CUsusariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(listadoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(consultaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(345, 345, 345))
            .addGroup(CUsusariosLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Usuario", CUsusarios);

        CProductos.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setText("Nombre/ID");

        listadoProducto.setBackground(new java.awt.Color(255, 51, 153));
        listadoProducto.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        listadoProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imaneges/producto (1).png"))); // NOI18N
        listadoProducto.setText("Consultar producto  ");
        listadoProducto.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        listadoProducto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        listadoProducto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 536, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 662, Short.MAX_VALUE)
        );

        consultaProducto.setBackground(new java.awt.Color(255, 51, 153));
        consultaProducto.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        consultaProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imaneges/Conuslta.png"))); // NOI18N
        consultaProducto.setText("Buscar producto  ");
        consultaProducto.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        consultaProducto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        consultaProducto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        tblConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblConsulta);

        javax.swing.GroupLayout CProductosLayout = new javax.swing.GroupLayout(CProductos);
        CProductos.setLayout(CProductosLayout);
        CProductosLayout.setHorizontalGroup(
            CProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CProductosLayout.createSequentialGroup()
                .addGroup(CProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(CProductosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(CProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(referenciaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(CProductosLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(listadoProducto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(consultaProducto)
                        .addGap(71, 71, 71)))
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CProductosLayout.setVerticalGroup(
            CProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CProductosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 290, Short.MAX_VALUE))
            .addGroup(CProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(referenciaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(listadoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(consultaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Producto", CProductos);

        CProveedor.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Empresa/ID");

        referenciaProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                referenciaProveedorActionPerformed(evt);
            }
        });

        listadoProveedor.setBackground(new java.awt.Color(255, 51, 153));
        listadoProveedor.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        listadoProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imaneges/listado.png"))); // NOI18N
        listadoProveedor.setText("Listado de proveedores");
        listadoProveedor.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        listadoProveedor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        listadoProveedor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        consultaProveedor.setBackground(new java.awt.Color(255, 51, 153));
        consultaProveedor.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        consultaProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imaneges/Conuslta.png"))); // NOI18N
        consultaProveedor.setText("Buscar proveedor");
        consultaProveedor.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        consultaProveedor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        consultaProveedor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        tblProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblProveedor);

        javax.swing.GroupLayout CProveedorLayout = new javax.swing.GroupLayout(CProveedor);
        CProveedor.setLayout(CProveedorLayout);
        CProveedorLayout.setHorizontalGroup(
            CProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CProveedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CProveedorLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(listadoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(313, 313, 313)
                        .addComponent(consultaProveedor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(CProveedorLayout.createSequentialGroup()
                        .addGroup(CProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CProveedorLayout.createSequentialGroup()
                                .addGroup(CProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 801, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 63, Short.MAX_VALUE))
                            .addComponent(referenciaProveedor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        CProveedorLayout.setVerticalGroup(
            CProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CProveedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(referenciaProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(listadoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(consultaProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(319, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Proveedor", CProveedor);

        CCat.setBackground(new java.awt.Color(255, 255, 255));

        jLabel16.setText("Nombre de la categoria");

        referenciaCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                referenciaCatActionPerformed(evt);
            }
        });

        jPanel8.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 304, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 659, Short.MAX_VALUE)
        );

        listadoCat.setBackground(new java.awt.Color(255, 51, 153));
        listadoCat.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        listadoCat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imaneges/listado.png"))); // NOI18N
        listadoCat.setText("Listado de categoria");
        listadoCat.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        listadoCat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        listadoCat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        consultaCat.setBackground(new java.awt.Color(255, 51, 153));
        consultaCat.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        consultaCat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imaneges/Conuslta.png"))); // NOI18N
        consultaCat.setText("Buscar categoria");
        consultaCat.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        consultaCat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        consultaCat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        tblCat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblCat);

        javax.swing.GroupLayout CCatLayout = new javax.swing.GroupLayout(CCat);
        CCat.setLayout(CCatLayout);
        CCatLayout.setHorizontalGroup(
            CCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CCatLayout.createSequentialGroup()
                .addGroup(CCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CCatLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(CCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CCatLayout.createSequentialGroup()
                                .addGroup(CCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(referenciaCat, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 232, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(CCatLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(listadoCat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(consultaCat)
                        .addGap(132, 132, 132)))
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        CCatLayout.setVerticalGroup(
            CCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CCatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(referenciaCat, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(listadoCat, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(consultaCat, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(CCatLayout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 294, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Categoria", CCat);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addGap(100, 100, 100))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void referenciaProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_referenciaProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_referenciaProveedorActionPerformed

    private void referenciaCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_referenciaCatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_referenciaCatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel CCat;
    public javax.swing.JPanel CProductos;
    public javax.swing.JPanel CProveedor;
    public javax.swing.JPanel CUsusarios;
    public javax.swing.JLabel consultaCat;
    public javax.swing.JLabel consultaProducto;
    public javax.swing.JLabel consultaProveedor;
    public javax.swing.JLabel consultaUsuario;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel16;
    public javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel4;
    public javax.swing.JPanel jPanel5;
    public javax.swing.JPanel jPanel6;
    public javax.swing.JPanel jPanel8;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JLabel listadoCat;
    public javax.swing.JLabel listadoProducto;
    public javax.swing.JLabel listadoProveedor;
    public javax.swing.JLabel listadoUsuario;
    public javax.swing.JTextField referenciaCat;
    public javax.swing.JTextField referenciaProducto;
    public javax.swing.JTextField referenciaProveedor;
    public javax.swing.JTextField referenciaUsuario;
    public javax.swing.JTable tblCat;
    public javax.swing.JTable tblConsulta;
    public javax.swing.JTable tblProveedor;
    public javax.swing.JTable tblUsuario;
    // End of variables declaration//GEN-END:variables
}
