/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas;

/**
 *
 * @author jl393
 */
public class vistaCambios extends javax.swing.JPanel {

    /**
     * Creates new form Cambios
     */
    public vistaCambios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAltas = new javax.swing.JTabbedPane();
        altasUsuario = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        nombreUsuario = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        maternoUsuario = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        paternoUsuario = new javax.swing.JTextField();
        telefonoUsuario = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        btnRUsuario = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btnRUsuario1 = new javax.swing.JLabel();
        panelProducto = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        nombreProducto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        proveedorProducto = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        categoriaProducto = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        descripcionProducto = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        compraProducto = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        ventaProducto = new javax.swing.JTextField();
        btnRProducto = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnRUsuario2 = new javax.swing.JLabel();
        panelProveedor = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        empresaProveedor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nombreProveedor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        telefonoProveedor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        emailProveedor = new javax.swing.JTextField();
        btnRProveedor = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnRUsuario3 = new javax.swing.JLabel();

        panelAltas.setBackground(new java.awt.Color(255, 255, 255));
        panelAltas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        altasUsuario.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setText("Nombre");

        jLabel12.setText("Apellido materno");

        maternoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maternoUsuarioActionPerformed(evt);
            }
        });

        jLabel13.setText("Apellido paterno");

        telefonoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonoUsuarioActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 307, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 702, Short.MAX_VALUE)
        );

        btnRUsuario.setBackground(new java.awt.Color(255, 51, 153));
        btnRUsuario.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnRUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imaneges/usuario (1).png"))); // NOI18N
        btnRUsuario.setText(" Rregistrar Cambios  ");
        btnRUsuario.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnRUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRUsuario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabel17.setText("Telefono");

        btnRUsuario1.setBackground(new java.awt.Color(255, 51, 153));
        btnRUsuario1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnRUsuario1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imaneges/usuario (1).png"))); // NOI18N
        btnRUsuario1.setText("Consultar Usuario  ");
        btnRUsuario1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnRUsuario1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRUsuario1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout altasUsuarioLayout = new javax.swing.GroupLayout(altasUsuario);
        altasUsuario.setLayout(altasUsuarioLayout);
        altasUsuarioLayout.setHorizontalGroup(
            altasUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(altasUsuarioLayout.createSequentialGroup()
                .addGroup(altasUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(altasUsuarioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(altasUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, altasUsuarioLayout.createSequentialGroup()
                                .addGroup(altasUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(maternoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(altasUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(altasUsuarioLayout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(paternoUsuario)))
                            .addComponent(nombreUsuario)
                            .addGroup(altasUsuarioLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(0, 623, Short.MAX_VALUE))
                            .addComponent(telefonoUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, altasUsuarioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, altasUsuarioLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(btnRUsuario1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRUsuario)
                        .addGap(89, 89, 89)))
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        altasUsuarioLayout.setVerticalGroup(
            altasUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(altasUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(altasUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(altasUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maternoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paternoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jLabel17)
                .addGap(27, 27, 27)
                .addComponent(telefonoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(altasUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(altasUsuarioLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 99, Short.MAX_VALUE))
        );

        panelAltas.addTab("Usuario", altasUsuario);

        panelProducto.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setText("Nombre");

        jLabel6.setText("Categoria");

        proveedorProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        proveedorProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proveedorProductoActionPerformed(evt);
            }
        });

        jLabel7.setText("Proveedor");

        categoriaProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        categoriaProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoriaProductoActionPerformed(evt);
            }
        });

        jLabel8.setText("Descripcion");

        jLabel9.setText("Compra");

        compraProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compraProductoActionPerformed(evt);
            }
        });

        jLabel10.setText("Venta");

        ventaProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ventaProductoActionPerformed(evt);
            }
        });

        btnRProducto.setBackground(new java.awt.Color(255, 51, 153));
        btnRProducto.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnRProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imaneges/producto (1).png"))); // NOI18N
        btnRProducto.setText("Consultar Producto  ");
        btnRProducto.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnRProducto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRProducto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 662, Short.MAX_VALUE)
        );

        btnRUsuario2.setBackground(new java.awt.Color(255, 51, 153));
        btnRUsuario2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnRUsuario2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imaneges/usuario (1).png"))); // NOI18N
        btnRUsuario2.setText(" Rregistrar Cambios  ");
        btnRUsuario2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnRUsuario2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRUsuario2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout panelProductoLayout = new javax.swing.GroupLayout(panelProducto);
        panelProducto.setLayout(panelProductoLayout);
        panelProductoLayout.setHorizontalGroup(
            panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProductoLayout.createSequentialGroup()
                .addGroup(panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelProductoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(descripcionProducto)
                                .addGroup(panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(categoriaProducto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(proveedorProducto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(nombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel6)))
                                            .addComponent(jLabel7)))
                                    .addComponent(jLabel8)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProductoLayout.createSequentialGroup()
                                .addGroup(panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(compraProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(46, 46, 46)
                                .addGroup(panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(ventaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(panelProductoLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(btnRProducto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRUsuario2)
                        .addGap(82, 82, 82)))
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelProductoLayout.setVerticalGroup(
            panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(categoriaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(proveedorProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descripcionProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelProductoLayout.createSequentialGroup()
                        .addGroup(panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(compraProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ventaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnRUsuario2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelProductoLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 139, Short.MAX_VALUE))
        );

        panelAltas.addTab("Producto", panelProducto);

        panelProveedor.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Empresa");

        empresaProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empresaProveedorActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre");

        nombreProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreProveedorActionPerformed(evt);
            }
        });

        jLabel3.setText("Telefono");

        telefonoProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonoProveedorActionPerformed(evt);
            }
        });

        jLabel4.setText("Email");

        emailProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailProveedorActionPerformed(evt);
            }
        });

        btnRProveedor.setBackground(new java.awt.Color(255, 51, 153));
        btnRProveedor.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnRProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imaneges/proveedor (1).png"))); // NOI18N
        btnRProveedor.setText("Consultar Proveedor");
        btnRProveedor.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnRProveedor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRProveedor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 266, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btnRUsuario3.setBackground(new java.awt.Color(255, 51, 153));
        btnRUsuario3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnRUsuario3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imaneges/usuario (1).png"))); // NOI18N
        btnRUsuario3.setText(" Rregistrar Cambios  ");
        btnRUsuario3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnRUsuario3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRUsuario3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout panelProveedorLayout = new javax.swing.GroupLayout(panelProveedor);
        panelProveedor.setLayout(panelProveedorLayout);
        panelProveedorLayout.setHorizontalGroup(
            panelProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProveedorLayout.createSequentialGroup()
                .addGroup(panelProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelProveedorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(emailProveedor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                            .addGroup(panelProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nombreProveedor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                                    .addComponent(empresaProveedor, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(telefonoProveedor, javax.swing.GroupLayout.Alignment.LEADING))
                                .addComponent(jLabel4)))
                        .addGap(18, 18, 18))
                    .addGroup(panelProveedorLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(btnRProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 315, Short.MAX_VALUE)
                        .addComponent(btnRUsuario3)
                        .addGap(98, 98, 98)))
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelProveedorLayout.setVerticalGroup(
            panelProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProveedorLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(empresaProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nombreProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(telefonoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRUsuario3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(224, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelAltas.addTab("Proveedor", panelProveedor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelAltas)
                .addGap(100, 100, 100))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelAltas)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void maternoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maternoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maternoUsuarioActionPerformed

    private void proveedorProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proveedorProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_proveedorProductoActionPerformed

    private void categoriaProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoriaProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoriaProductoActionPerformed

    private void compraProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compraProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_compraProductoActionPerformed

    private void ventaProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ventaProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ventaProductoActionPerformed

    private void empresaProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empresaProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empresaProveedorActionPerformed

    private void nombreProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreProveedorActionPerformed

    private void telefonoProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonoProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonoProveedorActionPerformed

    private void emailProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailProveedorActionPerformed

    private void telefonoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonoUsuarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel altasUsuario;
    public javax.swing.JLabel btnRProducto;
    public javax.swing.JLabel btnRProveedor;
    public javax.swing.JLabel btnRUsuario;
    public javax.swing.JLabel btnRUsuario1;
    public javax.swing.JLabel btnRUsuario2;
    public javax.swing.JLabel btnRUsuario3;
    public javax.swing.JComboBox<String> categoriaProducto;
    public javax.swing.JTextField compraProducto;
    public javax.swing.JTextField descripcionProducto;
    public javax.swing.JTextField emailProveedor;
    public javax.swing.JTextField empresaProveedor;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel17;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel4;
    public javax.swing.JPanel jPanel5;
    public javax.swing.JPanel jPanel6;
    public javax.swing.JTextField maternoUsuario;
    public javax.swing.JTextField nombreProducto;
    public javax.swing.JTextField nombreProveedor;
    public javax.swing.JTextField nombreUsuario;
    private javax.swing.JTabbedPane panelAltas;
    private javax.swing.JPanel panelProducto;
    private javax.swing.JPanel panelProveedor;
    public javax.swing.JTextField paternoUsuario;
    public javax.swing.JComboBox<String> proveedorProducto;
    public javax.swing.JTextField telefonoProveedor;
    public javax.swing.JTextField telefonoUsuario;
    public javax.swing.JTextField ventaProducto;
    // End of variables declaration//GEN-END:variables
}
